<?php
/**
* @author Vaclav Cerny, https://vasekcerny.cz/
* @license https://www.apache.org/licenses/LICENSE-2.0 Apache License, Version 2.0
* @license https://www.gnu.org/licenses/gpl-2.0.html GNU General Public License, version 2 (one or other)
*/
class AdminerB64 {
        function selectVal($val, $link, $field, $original) {
        if (preg_match("~parameters|vars|changed_fields|field_data|volatile_vars|settings~", $field["field"])) {
		        if(!is_null($val))          return "<strong>B64</strong> ".base64_decode($val);
        }
        if (preg_match("~started_on|created_on~", $field["field"])) {
		        if(!is_null($val))          return "<strong>Timestamp:</strong>".  date("Y-m-d H:i:s", $val);;
        }
        
        if (preg_match("~table_num~", $field["field"])) {
          
          
          
		        if(!is_null($val)) {
              $Tables=array(1 =>"ca_acl" 									,
              2 =>"ca_application_vars"						,
              3 =>"ca_attribute_values"						,
              4 =>"ca_attributes"								,
              5 =>"ca_change_log"								,
              6 =>"ca_change_log_subjects"					,
              7 =>"ca_representation_annotations_x_entities"	,
              8 =>"ca_representation_annotations_x_objects"	,
              9 =>"ca_representation_annotations_x_occurrences"		,
              10 =>"ca_representation_annotations_x_places"			,
              11 =>"ca_representation_annotations_x_vocabulary_terms"	,
              12 =>"ca_collection_labels"						,
              13 =>"ca_collections"							,
              14 =>"ca_collections_x_collections"				,
              15 =>"ca_collections_x_vocabulary_terms"			,
              16 =>"ca_search_form_type_restrictions" 			,
              17 =>"ca_data_import_events"						,
              18 =>"ca_data_import_items"						,
              20 =>"ca_entities"								,
              21 =>"ca_entities_x_collections"					,
              22 =>"ca_entities_x_occurrences"					,
              23 =>"ca_entities_x_places"						,
              24 =>"ca_entities_x_vocabulary_terms"			,
              25 =>"ca_entity_labels"							,
              26 =>"ca_entities_x_entities"					,
              30 =>"ca_groups_x_roles"							,
              31 =>"ca_ips"									,
              32 =>"ca_list_item_labels"						,
              33 =>"ca_list_items"								,
              34 =>"ca_list_items_x_list_items"				,
              35 =>"ca_list_labels"							,
              36 =>"ca_lists"									,
              37 =>"ca_locales"								,
              40 =>"ca_object_lot_labels"						,
              41 =>"ca_metadata_element_labels"				,
              42 =>"ca_metadata_elements"						,
              43 =>"ca_metadata_type_restrictions"				,
              44 =>"ca_multipart_idno_sequences"				,
              50 =>"ca_object_labels"							,
              51 =>"ca_object_lots"							,
              52 =>"ca_object_lots_x_collections"				,
              53 =>"ca_object_lots_x_entities"					,
              54 =>"ca_object_lots_x_occurrences"				,
              55 =>"ca_object_lots_x_places"					,
              56 =>"ca_object_representations"					,
              57 =>"ca_objects"								,
              58 =>"ca_objects_x_collections"					,
              59 =>"ca_objects_x_entities"						,
              61 =>"ca_objects_x_object_representations"		,
              62 =>"ca_objects_x_objects"						,
              63 =>"ca_objects_x_occurrences"					,
              64 =>"ca_objects_x_places"						,
              65 =>"ca_objects_x_vocabulary_terms"				,
              66 =>"ca_occurrence_labels"						,
              67 =>"ca_occurrences"							,
              68 =>"ca_occurrences_x_collections"				,
              69 =>"ca_occurrences_x_occurrences"				,
              70 =>"ca_occurrences_x_vocabulary_terms"			,
              71 =>"ca_place_labels"							,
              72 =>"ca_places"									,
              73 =>"ca_places_x_collections"					,
              74 =>"ca_places_x_occurrences"					,
              75 =>"ca_places_x_places"						,
              76 =>"ca_places_x_vocabulary_terms"				,
              77 =>"ca_relationship_relationships"				,
              78 =>"ca_relationship_type_labels"				,
              79 =>"ca_relationship_types"						,
              82 =>"ca_representation_annotations"				,
              83 =>"ca_representation_annotation_labels"		,
              85 =>"ca_object_representations_x_entities"				,
              86 =>"ca_object_representations_x_occurrences"			,
              87 =>"ca_object_representations_x_places"				,
              88 =>"ca_storage_location_labels"				,
              89 =>"ca_storage_locations"						,
              90 =>"ca_task_queue"								,
              91 =>"ca_user_groups"							,
              92 =>"ca_user_roles"								,
              94 =>"ca_users"									,
              95 =>"ca_users_x_groups"							,
              96 =>"ca_users_x_roles"							,
              97 =>"ca_editor_ui_bundle_placements"			,
              98 =>"ca_editor_ui_labels"						,
              99 =>"ca_editor_ui_screen_labels"				,
              100 =>"ca_editor_ui_screens"						,
              101 =>"ca_editor_uis"								,
              102 =>"ca_editor_uis_x_user_groups"				,
              103 =>"ca_sets"									,
              104 =>"ca_set_labels"								,
              105 =>"ca_set_items"								,
              106 =>"ca_set_item_labels"						,
              107 =>"ca_sets_x_user_groups"						,
              108 =>"ca_object_representation_labels"			,
              109 =>"ca_item_comments"							,
              110 =>"ca_item_tags"								,
              111 =>"ca_items_x_tags"							,
              113 =>"ca_editor_uis_x_roles"						,
              114 =>"ca_editor_ui_screens_x_roles"				,
              115 =>"ca_object_lots_x_vocabulary_terms"			,
              116 =>"ca_object_representations_x_vocabulary_terms"		,
              119 =>"ca_objects_x_storage_locations"			,
              120 =>"ca_object_lots_x_storage_locations"		,
              121 =>"ca_search_forms"							,
              122 =>"ca_search_form_labels"						,
              123 =>"ca_object_representation_multifiles"		,
              124 =>"ca_bundle_displays"						,
              125 =>"ca_bundle_display_placements"				,
              126 =>"ca_bundle_display_labels"					,
              127 =>"ca_bundle_displays_x_user_groups"			,
              131 =>"ca_editor_ui_screen_type_restrictions"		,
              132 =>"ca_collections_x_storage_locations"		,
              133 =>"ca_loans"									,
              134 =>"ca_loan_labels"							,
              135 =>"ca_loans_x_objects"						,
              136 =>"ca_loans_x_entities"						,
              137 =>"ca_movements"								,
              138 =>"ca_movement_labels"						,
              139 =>"ca_movements_x_objects"					,
              140 =>"ca_movements_x_object_lots"				,
              141 =>"ca_movements_x_entities"					,
              143 =>"ca_loans_x_movements"						,
              144 =>"ca_watch_list"								,
              145 =>"ca_user_notes"								,
              146 =>"ca_data_import_event_log"          ,
              147 =>"ca_search_forms_x_user_groups"	 ,
              148 =>"ca_search_forms_x_users"	 ,
              149 =>"ca_bundle_displays_x_users"	 ,
              150 =>"ca_sets_x_users"	 ,
              151 =>"ca_editor_uis_x_users"	 ,
              152 =>"ca_search_form_placements" ,
              153 =>"ca_tours" ,
              154 =>"ca_tour_labels" ,
              155 =>"ca_tour_stops" ,
              156 =>"ca_tour_stop_labels" ,
              157 =>"ca_tour_stops_x_objects"	 ,
              158 =>"ca_tour_stops_x_entities"	 ,
              159 =>"ca_tour_stops_x_places"	 ,
              160 =>"ca_tour_stops_x_occurrences"	 ,
              161 =>"ca_tour_stops_x_collections"	 ,
              162 =>"ca_tour_stops_x_vocabulary_terms"	 ,
              163 =>"ca_tour_stops_x_tour_stops"	 ,
              164 =>"ca_bookmark_folders" ,
              165 =>"ca_bookmarks" ,
              172 =>"ca_object_representations_x_collections" ,
              173 =>"ca_object_representations_x_storage_locations" ,
              174 =>"ca_object_representations_x_object_representations" ,
              177 =>"ca_entities_x_storage_locations" ,
              178 =>"ca_loans_x_collections" ,
              179 =>"ca_loans_x_object_lots" ,
              180 =>"ca_loans_x_occurrences" ,
              181 =>"ca_loans_x_places" ,
              182 =>"ca_loans_x_storage_locations" ,
              183 =>"ca_loans_x_vocabulary_terms" ,
              184 =>"ca_loans_x_loans" ,
              185 =>"ca_movements_x_collections" ,
              186 =>"ca_movements_x_occurrences" ,
              187 =>"ca_movements_x_places" ,
              188 =>"ca_movements_x_storage_locations" ,
              189 =>"ca_movements_x_vocabulary_terms" ,
              190 =>"ca_movements_x_movements" ,
              191 =>"ca_places_x_storage_locations" ,
              192 =>"ca_occurrences_x_storage_locations" ,
              193 =>"ca_storage_locations_x_vocabulary_terms" ,
              194 =>"ca_storage_locations_x_storage_locations" ,
              198 =>"ca_editor_ui_type_restrictions" ,
              199 =>"ca_object_lots_x_object_representations" ,
              200 =>"ca_loans_x_object_representations" ,
              201 =>"ca_movements_x_object_representations" ,
              202 =>"ca_data_importers" ,
              203 =>"ca_data_importer_labels" ,
              204 =>"ca_data_importer_groups" ,
              205 =>"ca_data_importer_items" ,
              206 =>"ca_data_importer_log" ,
              207 =>"ca_data_importer_log_items" ,
              208 =>"ca_data_exporters" ,
              209 =>"ca_data_exporter_labels" ,
              210 =>"ca_data_exporter_items" ,
              211 =>"ca_object_lots_x_object_lots" ,
              212 =>"ca_bundle_display_type_restrictions" ,
              213 =>"ca_object_representation_captions" ,
              214 =>"ca_metadata_dictionary_entries" ,
              215 =>"ca_metadata_dictionary_rules" ,
              216 =>"ca_attribute_value_multifiles" ,
              217 =>"ca_metadata_dictionary_rule_violations" ,
              218 =>"ca_object_checkouts" ,
              219 =>"ca_user_representation_annotations" ,
              220 =>"ca_user_representation_annotation_labels" ,
              221 =>"ca_user_representation_annotations_x_entities"	,
              222 =>"ca_user_representation_annotations_x_objects"	,
              223 =>"ca_user_representation_annotations_x_occurrences"		,
              224 =>"ca_user_representation_annotations_x_places"			,
              225 =>"ca_user_representation_annotations_x_vocabulary_terms"	,
              226 =>"ca_search_indexing_queue" ,
              227 =>"ca_editor_ui_screens_x_user_groups" ,
              228 =>"ca_editor_ui_screens_x_users" ,
              229 =>"ca_guids" ,
              230 =>"ca_replication_log" ,
              231 =>"ca_user_sorts" ,
              232 =>"ca_user_sort_items" ,
              233 =>"ca_notifications" ,
              234 =>"ca_notification_subjects" ,
              235 =>"ca_site_pages" ,
              236 =>"ca_site_templates" ,
              237 =>"ca_site_page_media" ,
              238 =>"ca_metadata_alert_rules" ,
              239 =>"ca_metadata_alert_rule_labels"	,
              240 =>"ca_metadata_alert_triggers" ,
              241 =>"ca_metadata_alert_rules_x_user_groups" ,
              242 =>"ca_metadata_alert_rules_x_users" ,
              243 =>"ca_metadata_alert_rule_type_restrictions" );
              if(isset($Tables[$val])){
                      return $val . " <small>".$Tables[$val]."</small>";
                
              }
              
            }   
        }
        
        
        
        }
}

